version: '3.8'

services:
  user-service:
    build:
      context: ./user-service
      dockerfile: Dockerfile
    container_name: user-service
    ports:
      - "4000:4000"
    environment:
      - DB_HOST=user-db
      - DB_USER=root
      - DB_PASSWORD=root
      - DB_NAME=userdb
      - PORT=4000
    depends_on:
      user-db:
        condition: service_healthy
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "--host=user-db", "--user=root", "--password=root"]
      interval: 10s
      timeout: 5s
      retries: 5
      start_period: 30s

  user-db:
    image: mysql:8
    restart: always
    environment:
      - MYSQL_ROOT_PASSWORD=root
      - MYSQL_DATABASE=userdb
    ports:
      - "3307:3306"
    volumes:
      - user-db-data:/var/lib/mysql
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "127.0.0.1", "-u", "root", "-proot"]
      interval: 10s
      timeout: 5s
      retries: 5
      start_period: 30s


volumes:
  user-db-data:
